// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3_RICCyBXipA1WDJROxn1nlFpzjqajOk',
    appId: '1:697866043206:web:166e44a14035bb7b202f47',
    messagingSenderId: '697866043206',
    projectId: 'vetrina-mia',
    authDomain: 'vetrina-mia.firebaseapp.com',
    storageBucket: 'vetrina-mia.appspot.com',
    measurementId: 'G-D82627PB53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCus2KVB8xu7jC-WGPAkcqh1WWFMuLauc',
    appId: '1:697866043206:android:27678a0e5b195143202f47',
    messagingSenderId: '697866043206',
    projectId: 'vetrina-mia',
    storageBucket: 'vetrina-mia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaR20RfVeD0QOhe3GvX3aSy_obYbVXsXM',
    appId: '1:697866043206:ios:31aa538d1074a425202f47',
    messagingSenderId: '697866043206',
    projectId: 'vetrina-mia',
    storageBucket: 'vetrina-mia.appspot.com',
    androidClientId: '697866043206-2sqj94q6em263ved7k6bfj36nl0a8g0d.apps.googleusercontent.com',
    iosClientId: '697866043206-0uid6ej43bt007scf1tu02j7mjgr1fcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetrinamiaCn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaR20RfVeD0QOhe3GvX3aSy_obYbVXsXM',
    appId: '1:697866043206:ios:31aa538d1074a425202f47',
    messagingSenderId: '697866043206',
    projectId: 'vetrina-mia',
    storageBucket: 'vetrina-mia.appspot.com',
    androidClientId: '697866043206-2sqj94q6em263ved7k6bfj36nl0a8g0d.apps.googleusercontent.com',
    iosClientId: '697866043206-0uid6ej43bt007scf1tu02j7mjgr1fcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetrinamiaCn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3_RICCyBXipA1WDJROxn1nlFpzjqajOk',
    appId: '1:697866043206:web:42f00a8c6cac7aad202f47',
    messagingSenderId: '697866043206',
    projectId: 'vetrina-mia',
    authDomain: 'vetrina-mia.firebaseapp.com',
    storageBucket: 'vetrina-mia.appspot.com',
    measurementId: 'G-BNQEQKPXQJ',
  );
}
